type TcAdviceDefinition {
  name: String!
  description: String!
  condition: TcAdviceDefinitionCondition
}

type TcAdviceDefinitionCondition {
  sexIn: [TcProfileSexEnum!]! @default(value: "[]")
  minWeight: Float
  insuranceCompanyCodes: [Int!]!
}