type TcVaccinatedDisease @meta(nameField: "disease"){
  disease: String!
  vaccines: [TcVaccine!]! @default(value: "[]")
}

type TcVaccine {
  name: String
  doseCount: Int
  doseInterval: [TcDoseInterval!]! @default(value: "[]")
}

type TcDoseInterval {
  afterDose: Int
  intervalDays: Int
}
