type TcProfile {
  name: String!
  email: String
  phoneNumber: String
  "Date of birth"
  birthDate: DateTime
  "Biological sex"
  sex: TcProfileSexEnum
  "Height in meters"
  height: Float
  "Weight in kilograms"
  weight: Float
  "Body-mass index (weight / height^2)"
  bmi: Float @precomputed
  "Rodne cislo"
  birthNumber: String
  "Insurance Document Number"
  insuranceDocumentNumber: String
  "Date of insurance expiration"
  insuranceExpiration: DateTime
  "Information about insurance"
  tcInsuranceCompany: TcInsuranceCompany @relation
}

enum TcProfileSexEnum {
  male
  female
}
